liczba_1 = input('Podaj liczbę w postaci binarnej (6 znaków 0/1)')
asa = str(liczba_1)
a = int(asa[0])
b = int(asa[1])
c = int(asa[2])
d = int(asa[3])
e = int(asa[4])
f = int(asa[-1])
print((a*32) + (b*16) + (c*8) + (d*4) + (e*2) + (f*1))
